// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UnitTestCompiladorGarGar
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinListItem uIQuestionSignintovoteListItem = this.UISystemIOFileNotFoundWindow.UIItemList.UIQuestionSignintovoteListItem;
            #endregion

            // Move 'Question Sign in to vote 0 Sign in to vote Noticed...' list item
            Mouse.StartDragging(uIQuestionSignintovoteListItem, new Point(164, 128));
            Mouse.StopDragging(uIQuestionSignintovoteListItem, 237, 154);
        }
        
        #region Properties
        public UISystemIOFileNotFoundWindow UISystemIOFileNotFoundWindow
        {
            get
            {
                if ((this.mUISystemIOFileNotFoundWindow == null))
                {
                    this.mUISystemIOFileNotFoundWindow = new UISystemIOFileNotFoundWindow();
                }
                return this.mUISystemIOFileNotFoundWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISystemIOFileNotFoundWindow mUISystemIOFileNotFoundWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UISystemIOFileNotFoundWindow : WinWindow
    {
        
        public UISystemIOFileNotFoundWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "System.IO.FileNotFoundException: Could not load file or assembly \'Microsoft.Visua" +
                "lStudio.TestTools.UITest.WindowsStoreUtility, - Mozilla Firefox";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "MozillaWindowClass";
            this.WindowTitles.Add("System.IO.FileNotFoundException: Could not load file or assembly \'Microsoft.Visua" +
                    "lStudio.TestTools.UITest.WindowsStoreUtility, - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public UIItemList UIItemList
        {
            get
            {
                if ((this.mUIItemList == null))
                {
                    this.mUIItemList = new UIItemList(this);
                }
                return this.mUIItemList;
            }
        }
        #endregion
        
        #region Fields
        private UIItemList mUIItemList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemList : WinList
    {
        
        public UIItemList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("System.IO.FileNotFoundException: Could not load file or assembly \'Microsoft.Visua" +
                    "lStudio.TestTools.UITest.WindowsStoreUtility, - Mozilla Firefox");
            #endregion
        }
        
        #region Properties
        public WinListItem UIQuestionSignintovoteListItem
        {
            get
            {
                if ((this.mUIQuestionSignintovoteListItem == null))
                {
                    this.mUIQuestionSignintovoteListItem = new WinListItem(this);
                    #region Search Criteria
                    this.mUIQuestionSignintovoteListItem.SearchProperties[WinListItem.PropertyNames.Name] = @"Question Sign in to vote 0 Sign in to vote Noticed I wrote [TestClass] instead of [CodeduiTest] before class It works now Marked as answer by Fredrik Almén About Fredrik Almén Friday, December 05, 2014 1:07 PM Friday, December 05, 2014 1:07 PM Reply |Quote Avatar of Fredrik Almén Fredrik Almén 0 Points";
                    this.mUIQuestionSignintovoteListItem.WindowTitles.Add("System.IO.FileNotFoundException: Could not load file or assembly \'Microsoft.Visua" +
                            "lStudio.TestTools.UITest.WindowsStoreUtility, - Mozilla Firefox");
                    #endregion
                }
                return this.mUIQuestionSignintovoteListItem;
            }
        }
        #endregion
        
        #region Fields
        private WinListItem mUIQuestionSignintovoteListItem;
        #endregion
    }
}
